# Generated by Django 4.1.2 on 2022-10-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Cardiology 1', 'CARDIOLOGY 1'), ('Orthopadic 2', 'OTHOPADIC 2'), ('Neourology 3', 'NEOUROLOGY 3'), ('Dentist 4', 'DENTIST 4'), ('Gynacology 5', 'GYNACOLOGY 5'), ('General 6', 'GENERAL 6')], default='General 6', max_length=15)),
                ('doctor', models.CharField(choices=[('Dr.Harish', 'DR.HARISH'), ('Dr.manish', 'DR.MANISH'), ('Dr.jignesh', 'DR.JIGNESH'), ('Dr.bhavesh', 'DR.BHAVESH'), ('Dr.rahul', 'DR.RAHUL'), ('Dr.karan', 'DR.KARAN')], default='Dr.karan', max_length=15)),
                ('f_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
