# Generated by Django 4.1.2 on 2022-10-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
