# Generated by Django 4.1.2 on 2022-10-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_date_alter_user_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
