# Generated by Django 4.1.2 on 2022-11-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ricrudoctor_remove_doctor_designation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppoUser',
        ),
    ]
