# Generated by Django 4.1.2 on 2022-11-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_user_appouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('p_contact', models.CharField(max_length=30)),
                ('p_address', models.CharField(max_length=250)),
                ('p_city', models.CharField(max_length=30)),
                ('p_state', models.CharField(max_length=30)),
            ],
        ),
    ]
