# Generated by Django 4.1.2 on 2022-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appouser',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'CARDIOLOGY'), ('Orthopadic', 'OTHOPADIC'), ('Neourology', 'NEOUROLOGY'), ('Dentist', 'DENTIST'), ('Gynacology', 'GYNACOLOGY'), ('General', 'GENERAL')], default='General', max_length=30),
        ),
        migrations.AlterField(
            model_name='appouser',
            name='doctor',
            field=models.CharField(choices=[('Dr.Harish Chauhan', 'DR.HARISH CHAUHAN'), ('Dr.Manish Malhotra', 'DR.MANISH MALHOTRA'), ('Dr.Helly Shah', 'DR.HELLY SHAH'), ('Dr.Bhavesh Patel', 'DR.BHAVESH PATEL'), ('Dr.Rahul PATEL', 'DR.RAHUL PATEL'), ('Dr.Karan Patel', 'DR.KARAN PATEL')], default='Dr.Karan Patel', max_length=30),
        ),
    ]
