# Generated by Django 4.1.2 on 2022-11-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_appouser_department_remove_appouser_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RicruDoctor',
        ),
    ]
