# Generated by Django 4.1.2 on 2022-11-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_ricrudoctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='email',
            new_name='speciality',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='education',
        ),
        migrations.AddField(
            model_name='doctor',
            name='pic',
            field=models.FileField(default='', upload_to='doctor'),
        ),
    ]
