# Generated by Django 4.1.2 on 2022-11-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_email_doctor_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=30),
        ),
    ]
