# Generated by Django 4.1.2 on 2022-11-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_doctor_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='f_name',
            new_name='d_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='l_name',
            new_name='description',
        ),
    ]
