# Generated by Django 4.1.2 on 2022-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_f_name_doctor_d_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item', models.CharField(max_length=30)),
                ('service_icon', models.CharField(max_length=30)),
                ('service_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=330)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.CharField(max_length=350),
        ),
    ]
