# Generated by Django 4.1.2 on 2022-11-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_service_item_service_service_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_icon',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(max_length=300),
        ),
    ]
